# Generated by Django 5.0.12 on 2025-07-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_company_mobile_number_alter_company_phone'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('company', 'name')},
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
    ]
