# Generated by Django 5.0.12 on 2025-07-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('estimate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='estimate_number',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='estimate',
            unique_together={('company', 'estimate_number')},
        ),
    ]
