# Generated by Django 5.0.12 on 2025-08-11 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='overtime',
            name='description',
        ),
    ]
