# Generated by Django 5.0.12 on 2025-08-25 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_company_city_remove_company_country_and_more'),
        ('employee', '0050_alter_employee_joining_date'),
        ('overtime', '0003_alter_overtime_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overtime',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='overtime',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overtimes', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtimes', to='employee.employee'),
        ),
        migrations.AlterUniqueTogether(
            name='overtime',
            unique_together={('employee', 'date')},
        ),
        migrations.AlterModelTable(
            name='overtime',
            table='overtime',
        ),
    ]
