# Generated by Django 5.0.12 on 2025-08-25 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_company_city_remove_company_country_and_more'),
        ('overtime', '0004_alter_overtime_options_overtime_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overtime',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='overtime',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='overtime',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='overtime',
            table=None,
        ),
        migrations.RemoveField(
            model_name='overtime',
            name='status',
        ),
    ]
