# Generated by Django 5.0.12 on 2025-07-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='default_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
