# Generated by Django 5.0.12 on 2025-07-02 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employeeprofile_profile_picture'),
        ('leave_management', '0002_leavetype_default_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_days', models.PositiveIntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employee.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='leave_management.leavetype')),
            ],
            options={
                'db_table': 'leave_balance',
                'unique_together': {('employee', 'leave_type')},
            },
        ),
    ]
