# Generated by Django 5.0.12 on 2025-07-03 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('employee', '0005_employeeprofile_profile_picture'),
        ('leave_management', '0003_leavebalance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='leavebalance',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='accounts.company'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('company', 'employee', 'leave_type')},
        ),
    ]
