# Generated by Django 5.0.12 on 2025-07-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0004_alter_leavebalance_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='description',
        ),
    ]
