# Generated by Django 5.0.12 on 2025-08-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0005_remove_leavetype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='default_days',
            field=models.PositiveIntegerField(default=1, verbose_name='Default Days'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Add Leave Type'),
        ),
    ]
