# Generated by Django 5.0.12 on 2025-08-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0006_alter_leavetype_default_days_alter_leavetype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='assigned_to',
            field=models.CharField(choices=[('all', 'All Employees'), ('male', 'Male Employees'), ('female', 'Female Employees'), ('custom', 'Selected Employees')], default='all', max_length=10, verbose_name='Assign To'),
        ),
    ]
