# Generated by Django 5.0.12 on 2025-08-03 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0007_leavetype_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='assigned_to',
        ),
    ]
