# Generated by Django 5.0.12 on 2025-08-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0010_remove_leavetype_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='assigned_to',
            field=models.CharField(choices=[('all', 'All Employees'), ('male', 'Male Employees'), ('female', 'Female Employees'), ('custom', 'Custom Employees')], default='all', max_length=10),
        ),
    ]
