# Generated by Django 5.0.12 on 2025-08-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0011_leavetype_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='leavetype',
            name='carry_forward',
            field=models.CharField(choices=[('', 'Select Option'), ('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='eligibility',
            field=models.CharField(choices=[('', 'Select Employees'), ('all', 'All Employees'), ('male', 'Male Employees'), ('female', 'Female Employees')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='encashment',
            field=models.CharField(choices=[('', 'Select Option'), ('yes', 'Yes'), ('no', 'No')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='monthly_accrual',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='default_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
