# Generated by Django 5.0.12 on 2025-08-06 08:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_remove_policy_department_policy_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='file',
        ),
        migrations.AlterField(
            model_name='policy',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Description'),
        ),
    ]
