# Generated by Django 5.0.12 on 2025-07-08 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('employee', '0006_alter_employee_employee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Termination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termination_type', models.CharField(choices=[('Misconduct', 'Misconduct'), ('Layoff', 'Layoff'), ('Performance', 'Performance'), ('Other', 'Other')], default='Misconduct', max_length=50)),
                ('termination_date', models.DateField()),
                ('reason', models.TextField()),
                ('notice_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terminations', to='accounts.company')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
