# Generated by Django 5.0.12 on 2025-08-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('termination', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termination',
            name='termination_type',
            field=models.CharField(choices=[('Misconduct', 'Misconduct'), ('Layoff', 'Layoff'), ('Performance', 'Performance'), ('Other', 'Other')], max_length=50),
        ),
    ]
