# Generated by Django 5.0.12 on 2025-08-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To_Do', 'To Do'), ('In_Progress', 'In Progress'), ('Review', 'Review'), ('Completed', 'Completed')], default='todo', max_length=20),
        ),
    ]
