# Generated by Django 5.0.12 on 2025-08-02 12:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_company_logo'),
        ('clients', '0010_alter_client_client_name'),
        ('employee', '0030_alter_employeeprofile_options_and_more'),
        ('projects', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='projects/', verbose_name='Project File'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Rate'),
        ),
        migrations.AlterField(
            model_name='project',
            name='rate_type',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('fixed', 'Fixed')], max_length=10, verbose_name='Rate Type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Not Started', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leading_projects', to='employee.employee', verbose_name='Team Leader'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(related_name='project_memberships', to='employee.employee', verbose_name='Team Members'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee', verbose_name='Assigned To'),
        ),
        migrations.AlterField(
            model_name='task',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='tasks/', verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('To_Do', 'To Do'), ('In_Progress', 'In Progress'), ('Review', 'Review'), ('Completed', 'Completed')], default='To_Do', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Task Title'),
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='task_progress/', verbose_name='Attachment'),
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='percentage_complete',
            field=models.PositiveIntegerField(default=0, verbose_name='Percentage Complete'),
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='progress_description',
            field=models.TextField(verbose_name='Progress Description'),
        ),
        migrations.AlterField(
            model_name='taskprogress',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='projects.task', verbose_name='Task'),
        ),
    ]
