# Generated by Django 5.0.12 on 2025-08-03 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_client_alter_project_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='rate_type',
        ),
    ]
