# Generated by Django 5.0.12 on 2025-08-08 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_unique_together_and_more'),
        ('projects', '0005_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='department.department'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='Task ID'),
        ),
    ]
