# Generated by Django 5.0.12 on 2025-07-29 04:03

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='skills',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Python', 'Python'), ('Java', 'Java'), ('JavaScript', 'JavaScript'), ('HTML', 'HTML'), ('CSS', 'CSS'), ('Django', 'Django'), ('React', 'React'), ('Node.js', 'Node.js'), ('SQL', 'SQL'), ('MySQL', 'MySQL'), ('PostgreSQL', 'PostgreSQL'), ('MongoDB', 'MongoDB'), ('AWS', 'AWS'), ('Azure', 'Azure'), ('Docker', 'Docker'), ('Kubernetes', 'Kubernetes'), ('Git', 'Git'), ('Linux', 'Linux'), ('Agile', 'Agile'), ('Figma', 'Figma'), ('Photoshop', 'Photoshop'), ('Illustrator', 'Illustrator'), ('SEO', 'SEO'), ('Google Ads', 'Google Ads'), ('Excel', 'Excel'), ('Data Analysis', 'Data Analysis'), ('Machine Learning', 'Machine Learning'), ('Deep Learning', 'Deep Learning'), ('TensorFlow', 'TensorFlow'), ('PyTorch', 'PyTorch'), ('NLP', 'NLP'), ('Communication', 'Communication'), ('Teamwork', 'Teamwork'), ('Leadership', 'Leadership'), ('Project Management', 'Project Management'), ('Time Management', 'Time Management'), ('Creativity', 'Creativity'), ('Critical Thinking', 'Critical Thinking'), ('Problem Solving', 'Problem Solving'), ('Adaptability', 'Adaptability'), ('Testing', 'Testing'), ('REST API', 'REST API'), ('FastAPI', 'FastAPI'), ('Bootstrap', 'Bootstrap'), ('Tailwind CSS', 'Tailwind CSS'), ('TypeScript', 'TypeScript'), ('Vue.js', 'Vue.js'), ('Spring Boot', 'Spring Boot'), ('Flutter', 'Flutter'), ('Android Development', 'Android Development'), ('iOS Development', 'iOS Development'), ('Others', 'Others')], max_length=498),
        ),
    ]
