# Generated by Django 5.0.12 on 2025-07-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_remove_jobseekerprofile_skills_delete_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('High School', 'High School'), ('Diploma', 'Diploma'), ('Bachelor of Arts', 'Bachelor of Arts'), ('Bachelor of Science', 'Bachelor of Science'), ('Bachelor of Commerce', 'Bachelor of Commerce'), ('Bachelor of Technology', 'Bachelor of Technology'), ('Master of Arts', 'Master of Arts'), ('Master of Science', 'Master of Science'), ('Master of Commerce', 'Master of Commerce'), ('Master of Technology', 'Master of Technology'), ('MBA', 'MBA'), ('MCA', 'MCA'), ('PhD', 'PhD'), ('Other', 'Other')], max_length=255),
        ),
    ]
