# Generated by Django 5.0.12 on 2025-07-08 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('employee', '0006_alter_employee_employee_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('notice_date', models.DateField(help_text='Date notice was submitted')),
                ('resignation_date', models.DateField(help_text='Effective resignation date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resignations', to='accounts.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resignations', to='employee.employee')),
            ],
            options={
                'verbose_name': 'Resignation',
                'verbose_name_plural': 'Resignations',
                'ordering': ['-resignation_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='resignation',
            constraint=models.UniqueConstraint(fields=('company', 'employee', 'resignation_date'), name='unique_resignation_per_employee_date'),
        ),
    ]
