# Generated by Django 5.0.12 on 2025-08-06 07:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0039_educationdocument_governmentdocument'),
        ('resignation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resignation',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='resignation',
            name='unique_resignation_per_employee_date',
        ),
        migrations.RemoveField(
            model_name='resignation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='resignation',
            name='notice_date',
        ),
        migrations.AddField(
            model_name='resignation',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='resignation',
            name='last_working_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignation',
            name='mode_of_exit',
            field=models.CharField(blank=True, choices=[('resignation', 'Resignation'), ('retirement', 'Retirement')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='resignation',
            name='notice_period',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resignation',
            name='resignation_letter',
            field=models.FileField(blank=True, null=True, upload_to='resignation_letters/'),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='resignation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resignation',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20, null=True),
        ),
    ]
