# Generated by Django 5.0.12 on 2025-08-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_company_city_remove_company_country_and_more'),
        ('tax', '0002_alter_tax_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tax',
            unique_together={('company', 'name', 'percentage')},
        ),
    ]
