# Generated by Django 5.0.12 on 2025-08-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plan_type', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], max_length=10)),
                ('number_of_users', models.PositiveIntegerField()),
                ('number_of_projects', models.PositiveIntegerField()),
                ('storage_space', models.PositiveIntegerField(help_text='In GB')),
                ('description', models.TextField(blank=True)),
                ('status', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(blank=True, help_text='End date of the package', null=True)),
                ('module_list', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
