# Generated by Django 5.0.12 on 2025-07-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
