# Generated by Django 5.0.12 on 2025-07-31 15:42

import django.db.models.deletion
import payroll.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_managers'),
        ('employee', '0028_alter_bankdetails_options_and_more'),
        ('payroll', '0002_alter_payroll_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('item_type', models.CharField(choices=[('earning', 'Earning'), ('deduction', 'Deduction')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('assign_to', models.CharField(choices=[('all', 'All Employees'), ('specific', 'Specific Employees')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='payroll',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='payroll',
            name='unique_employee_month',
        ),
        migrations.RenameField(
            model_name='payroll',
            old_name='allowance',
            new_name='total_earnings',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='basic',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='conveyance',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='da',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='esi',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='fund',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='gross_salary',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='hra',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='labour_welfare',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='leave',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='medical_allowance',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='month',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='other_deductions',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='other_earnings',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='pf',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='professional_tax',
        ),
        migrations.RemoveField(
            model_name='payroll',
            name='tds',
        ),
        migrations.AddField(
            model_name='payroll',
            name='payroll_date',
            field=models.DateField(default=payroll.models.default_payroll_date),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payroll',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payitem',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
        migrations.AddField(
            model_name='payitem',
            name='specific_employees',
            field=models.ManyToManyField(blank=True, to='employee.employee'),
        ),
    ]
