# Generated by Django 5.0.12 on 2025-08-24 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_created_at_alter_job_description_and_more'),
        ('jobseeker', '0004_remove_education_medium_remove_education_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicant',
            name='jobseeker_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='jobseeker.jobseekerprofile'),
        ),
    ]
