# Generated by Django 5.0.12 on 2025-07-10 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('department', '0001_initial'),
        ('designation', '0001_initial'),
        ('employee', '0006_alter_employee_employee_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceAppraisal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('customer_experience', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert/Leader', 'Expert/Leader')], default='None', max_length=20)),
                ('marketing', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert/Leader', 'Expert/Leader')], default='None', max_length=20)),
                ('management', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert/Leader', 'Expert/Leader')], default='None', max_length=20)),
                ('administration', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert/Leader', 'Expert/Leader')], default='None', max_length=20)),
                ('presentation_skill', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert/Leader', 'Expert/Leader')], default='None', max_length=20)),
                ('quality_of_work', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert/Leader', 'Expert/Leader')], default='None', max_length=20)),
                ('efficiency', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert/Leader', 'Expert/Leader')], default='None', max_length=20)),
                ('integrity', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='None', max_length=20)),
                ('professionalism', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='None', max_length=20)),
                ('team_work', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='None', max_length=20)),
                ('critical_thinking', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='None', max_length=20)),
                ('conflict_management', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='None', max_length=20)),
                ('attendance', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='None', max_length=20)),
                ('ability_to_meet_deadline', models.CharField(choices=[('None', 'None'), ('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='None', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_appraisals', to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_experience', models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Average', 'Average'), ('Poor', 'Poor')], default='Average', max_length=20)),
                ('marketing', models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Average', 'Average'), ('Poor', 'Poor')], default='Average', max_length=20)),
                ('management', models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Average', 'Average'), ('Poor', 'Poor')], default='Average', max_length=20)),
                ('administration', models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Average', 'Average'), ('Poor', 'Poor')], default='Average', max_length=20)),
                ('presentation_skill', models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Average', 'Average'), ('Poor', 'Poor')], default='Average', max_length=20)),
                ('quality_of_work', models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Average', 'Average'), ('Poor', 'Poor')], default='Average', max_length=20)),
                ('efficiency', models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Average', 'Average'), ('Poor', 'Poor')], default='Average', max_length=20)),
                ('integrity', models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Average', 'Average'), ('Poor', 'Poor')], default='Average', max_length=20)),
                ('professionalism', models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Average', 'Average'), ('Poor', 'Poor')], default='Average', max_length=20)),
                ('teamwork', models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Average', 'Average'), ('Poor', 'Poor')], default='Average', max_length=20)),
                ('critical_thinking', models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Average', 'Average'), ('Poor', 'Poor')], default='Average', max_length=20)),
                ('conflict_management', models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Average', 'Average'), ('Poor', 'Poor')], default='Average', max_length=20)),
                ('attendance', models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Average', 'Average'), ('Poor', 'Poor')], default='Average', max_length=20)),
                ('punctuality', models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Average', 'Average'), ('Poor', 'Poor')], default='Average', max_length=20)),
                ('dependability', models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Average', 'Average'), ('Poor', 'Poor')], default='Average', max_length=20)),
                ('communication', models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Average', 'Average'), ('Poor', 'Poor')], default='Average', max_length=20)),
                ('decision_making', models.CharField(choices=[('Advanced', 'Advanced'), ('Intermediate', 'Intermediate'), ('Average', 'Average'), ('Poor', 'Poor')], default='Average', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designation.designation')),
            ],
        ),
    ]
