# Generated by Django 5.0.12 on 2025-07-31 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0028_alter_bankdetails_options_and_more'),
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performanceindicator',
            name='department',
        ),
        migrations.RemoveField(
            model_name='performanceindicator',
            name='designation',
        ),
        migrations.AddField(
            model_name='performanceindicator',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='performance_indicator', to='employee.employee'),
        ),
    ]
