# Generated by Django 5.0.12 on 2025-08-07 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_remove_company_city_remove_company_country_and_more'),
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_on', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='superadmin.package')),
            ],
            options={
                'unique_together': {('company', 'package')},
            },
        ),
    ]
