# Generated by Django 5.0.12 on 2025-07-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_city_company_country_company_fax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='mobile_number',
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
