# Generated by Django 5.0.12 on 2025-07-28 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='complete_profile',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^[\\d\\-+() ]*$', 'Enter a valid fax number')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('it', 'Information Technology'), ('finance', 'Finance'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('manufacturing', 'Manufacturing'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default='company_logos/default_logo.png', upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'Enter a valid 10-digit phone number')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.CharField(default='000000', max_length=20, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z -]+$', 'Enter a valid postal code')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='size',
            field=models.CharField(choices=[('small', 'Small (1–50)'), ('medium', 'Medium (51–250)'), ('large', 'Large (250+)')], max_length=10),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(default='https://example.com', validators=[django.core.validators.URLValidator()]),
        ),
    ]
