# Generated by Django 5.0.12 on 2025-08-01 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='fax',
        ),
    ]
