# Generated by Django 5.0.12 on 2025-08-01 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_company_fax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='company_logos/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='postal_code',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[0-9A-Za-z -]+$', 'Enter a valid postal code')]),
        ),
    ]
