# Generated by Django 5.0.12 on 2025-08-01 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_company_logo_alter_company_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
