# Generated by Django 5.0.12 on 2025-08-01 09:21

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_company_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='company_logos/', validators=[accounts.models.validate_image_format]),
        ),
    ]
