# Generated by Django 5.0.12 on 2025-05-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='day',
            field=models.CharField(blank=True, default='Monday', editable=False, max_length=9),
        ),
    ]
