# Generated by Django 4.2 on 2025-07-02 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('holiday', '0002_holiday_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='holiday',
            name='day',
            field=models.CharField(blank=True, editable=False, max_length=9),
        ),
    ]
