# Generated by Django 5.0.12 on 2025-07-28 10:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday', '0003_holiday_company_alter_holiday_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
