# Generated by Django 5.0.12 on 2025-07-08 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('department', '0001_initial'),
        ('designation', '0001_initial'),
        ('employee', '0006_alter_employee_employee_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_date', models.DateField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='accounts.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotions', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='employee.employee')),
                ('new_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_new', to='department.department')),
                ('new_designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_new', to='designation.designation')),
                ('old_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_old', to='department.department')),
                ('old_designation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_old', to='designation.designation')),
            ],
            options={
                'db_table': 'promotion',
                'ordering': ['-promotion_date'],
            },
        ),
    ]
