# Generated by Django 5.0.12 on 2025-07-11 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('designation', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='designation',
            unique_together={('department', 'name')},
        ),
        migrations.AlterModelTable(
            name='designation',
            table='designation',
        ),
    ]
