# Generated by Django 5.0.12 on 2025-08-02 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_company_logo'),
        ('department', '0002_alter_department_unique_together_and_more'),
        ('designation', '0002_alter_designation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='designation',
            unique_together={('company', 'department', 'name')},
        ),
    ]
