# Generated by Django 5.0.12 on 2025-08-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designation', '0003_alter_designation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20),
        ),
    ]
