# Generated by Django 5.0.12 on 2025-08-08 08:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_remove_company_city_remove_company_country_and_more'),
        ('department', '0002_alter_department_unique_together_and_more'),
        ('employee', '0045_alter_familymember_dependent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('expense_title', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(blank=True, choices=[('Travel', 'Travel'), ('Food', 'Food'), ('Accommodation', 'Accommodation'), ('Internet', 'Internet'), ('Office Supplies', 'Office Supplies'), ('Miscellaneous', 'Miscellaneous')], max_length=50, null=True)),
                ('expense_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid_by', models.CharField(blank=True, choices=[('Self', 'Self'), ('Company Advance', 'Company Advance'), ('Credit Card', 'Credit Card')], max_length=50, null=True)),
                ('expense_type', models.CharField(blank=True, choices=[('Reimbursable', 'Reimbursable'), ('Company Paid', 'Company Paid')], max_length=50, null=True)),
                ('receipt_upload', models.FileField(blank=True, null=True, upload_to='expense_receipts/')),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='employee.employee')),
            ],
        ),
    ]
